# Generated by Django 5.2.12 on 2026-04-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('wname', models.CharField(max_length=50)),
                ('wphone', models.CharField(max_length=10)),
                ('waddress', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='RestockOrder',
            fields=[
                ('restock_id', models.AutoField(primary_key=True, serialize=False)),
                ('restock_date', models.DateField()),
                ('restock_status', models.CharField(choices=[('Pending', 'Pending'), ('In transit', 'In transit'), ('Received', 'Received'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_orders', to='accounts.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_orders', to='stock.supplier')),
            ],
            options={
                'db_table': 'restock_order',
            },
        ),
        migrations.CreateModel(
            name='RestockDetail',
            fields=[
                ('restock_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_details', to='catalog.product')),
                ('restock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stock.restockorder')),
            ],
            options={
                'db_table': 'restock_detail',
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('aisle', models.CharField(max_length=5)),
                ('zone', models.CharField(max_length=20)),
                ('bin', models.CharField(max_length=20)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='stock.warehouse')),
            ],
            options={
                'db_table': 'warehouse_location',
                'unique_together': {('warehouse', 'aisle', 'zone', 'bin')},
            },
        ),
        migrations.AddField(
            model_name='restockorder',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_orders', to='stock.warehouselocation'),
        ),
    ]
